name: Build on push

on:
  push:
    branches:
      - master  # Adjust to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ..
      
      - name: Build project
        run: |
          cd client
          npm run build
